apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deploy.yml
- frontend/service.yml
- ingress.yml
- argocd/application.yml
images:
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newTag: 028fb034fd80c9e85463bb8ce4dc2855f3766046
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newTag: 028fb034fd80c9e85463bb8ce4dc2855f3766046
