apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deploy.yml
- frontend/service.yml
- ingress.yml
- argocd/application.yml
images:
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newTag: 910423b620b5a6b72813d0a9ce5f0f13f1a502df
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newTag: 8c8e3b3c9991f47248c5ff570bda8dcf656b8f39
