apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deploy.yml
- frontend/service.yml
- ingress.yml
- argocd/application.yml
images:
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newTag: d35c550c088600d25917c9aaef881a01e2ccca30
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newTag: 26aea83ce0ebd180246f0cd289c30bb6399a82cf
