apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deploy.yml
- frontend/service.yml
- ingress.yml

images:
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/backend
  newTag: 8037c79f2818ce5024d59cf2f5b6a782a3e9ba42
- name: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newName: 390402531423.dkr.ecr.us-east-1.amazonaws.com/colabkids/frontend
  newTag: 8037c79f2818ce5024d59cf2f5b6a782a3e9ba42
