apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colabkids-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/colabkids-2025/trabalho-ci-cd.git   # A URL base do repositório, sem /tree/main
    targetRevision: main   # O branch que você quer sincronizar (exemplo: 'main' ou 'HEAD')
    path: gitops  # O subdiretório no repositório que contém os manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
