apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: colabkids-project
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Learning CICD
  sourceRepos:
  - '*'
  destinations:
  - namespace: colabkids
    server: https://1BD5CBC0D55F8F3A85260769636B651E.gr7.us-east-1.eks.amazonaws.com
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  orphanedResources:
    warn: false
