---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:colabkids-2025/trabalho-ci-cd.git
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEQm5BZkVDNG91ZDlsQ3lwUkY1aGtsTFU4VGl5UFdNVHZRbmlBWGdNcEdqQUFBQUpodVlDZ0xibUFvCkN3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREJuQWZFQzRvdWQ5bEN5cFJGNWhrbExVOFRpeVBXTVR2UW5pQVhnTXBHakEKQUFBRUFMQkhFRG1PSExlVVJNdHRCaXJ3KzBjTVM3S0JWUUQ3a2NyYWpwWHBvejhjR2NCOFFMaWk1MzJVTEtsRVhtR1NVdApUeE9MSTlZeE85Q2VJQmVBeWthTUFBQUFEMnhsWVc1a2NtOUFURVZCVGtSU1R3RUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0

  insecure: "false"
  enableLfs: "true"

# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd
